name: practica_gasolinera
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  objectbox_generator: ^2.0.0
  path_provider: ^2.0.14

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
