// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/model/gasolinera_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 7668255884521740251),
      name: 'GasolineraModel',
      lastPropertyId: const IdUid(4, 3748378582664074870),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3072250791456828887),
            name: 'id',
            type: 6,
            flags: 129),
        ModelProperty(
            id: const IdUid(2, 9058073819961226278),
            name: 'capMax',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4267356927250595417),
            name: 'capMin',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3748378582664074870),
            name: 'porcentaje',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 7668255884521740251),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    GasolineraModel: EntityDefinition<GasolineraModel>(
        model: _entities[0],
        toOneRelations: (GasolineraModel object) => [],
        toManyRelations: (GasolineraModel object) => {},
        getId: (GasolineraModel object) => object.id,
        setId: (GasolineraModel object, int id) {
          object.id = id;
        },
        objectToFB: (GasolineraModel object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.capMax);
          fbb.addInt64(2, object.capMin);
          fbb.addInt64(3, object.porcentaje);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = GasolineraModel(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              capMax:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
              capMin:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              porcentaje:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [GasolineraModel] entity fields to define ObjectBox queries.
class GasolineraModel_ {
  /// see [GasolineraModel.id]
  static final id =
      QueryIntegerProperty<GasolineraModel>(_entities[0].properties[0]);

  /// see [GasolineraModel.capMax]
  static final capMax =
      QueryIntegerProperty<GasolineraModel>(_entities[0].properties[1]);

  /// see [GasolineraModel.capMin]
  static final capMin =
      QueryIntegerProperty<GasolineraModel>(_entities[0].properties[2]);

  /// see [GasolineraModel.porcentaje]
  static final porcentaje =
      QueryIntegerProperty<GasolineraModel>(_entities[0].properties[3]);
}
